### ISSUE TITLE
Dependencies ? ...

### ISSUE THREAD

**Issue by mistyn8** [Gibe/Umbraco.Community.AzureSSO#14]
Not sure if I'm missing the obvious here as dependency chains aren't in my usual scope expertise... ;-)
But.....

Do we need the explicit dependencies on `Umbraco.Cms.Core` as `Umbraco.Cms.Web.BackOffice` already include an implicit dependency?
![image](https://github.com/Gibe/Umbraco.Community.AzureSSO/assets/12418214/020edca1-3f87-4763-84f2-7475ae9639a2)

Also do we need the `Microsoft.Identity.Web.MicrosoftGraph` dependency, it would appear that the implicit `Microsoft.Identity.Web` is all that is required?

**Comment by stevetemple** [comment]
You're right we don't need Umbraco.Cms.Core 

PR #28 covers this

**Comment by stevetemple** [comment]
Will be in v2.0.0
