### ISSUE TITLE
Require Azure AD Authentication on all Front End Pages

### ISSUE THREAD

**Issue by benehudson** [Gibe/Umbraco.Community.AzureSSO#20]
I got Umbraco Azure AD SSO working for logging into the backoffice.

How would I leverage this package to require Azure AD Auth on all Front End pages?  We have a company site that we want only our employees to be able to login and see.

I tried using the same method I would on a non-Umbraco .NET Core web app.  But, that's failing.  I posted about it on our.umbraco.com here:  https://our.umbraco.com/forum/using-umbraco-and-getting-started//113043-add-oidc-azure-ad-auth-to-all-frontend-pages

With that not working, I'm hoping to be able to extend your package for Azure user authentication on all front end pages.

**Comment by stevetemple** [comment]
This one really is for the backoffice.

You'd typically implement something like that by requiring authentication for all visitors to the site. I'd be surprised if IIS doesn't have Entra ID authentication.

With Azure App Services there is an option to make all visits to the site require authentication, under Authentication -> Add an Identity Provider

![image](https://github.com/Gibe/Umbraco.Community.AzureSSO/assets/113788/388989ba-4710-4657-a976-7c8d763a46ae)

**Comment by stevetemple** [comment]
Out of scope for this package
