### ISSUE TITLE
Allow for multiple tenant configuration

### ISSUE THREAD

**Issue by Matthew-Wise** [Gibe/Umbraco.Community.AzureSSO#21]
Having the ability to let a client login using there Azure AD and an Agency been able to login using theirs would be a nice addition.

Happy to look at how this might be achieved

**Comment by stevetemple** [comment]
Yeah gonna happen because I need that for one of our clients

**Comment by Matthew-Wise** [comment]
Hey mate, 

Any update on this? We might are currently looking at our roadmap and this is on there as a possible task :) 

thanks
Matt

**Comment by stevetemple** [comment]
Working on it next week
