### ISSUE TITLE
Is Umbraco 13 supported

### ISSUE THREAD

**Issue by r-modica-cti** [Gibe/Umbraco.Community.AzureSSO#25]
Does the library support Umbraco 13?  I can see the project has been bumped to Support .Net 8, but the readme still mentions Umbraco 10 and 11 only rather then 13 and beyond?

**Comment by jdudleyweb** [comment]
I also am wondering if this is supported in Umbraco 13. I see it listed in the marketplace as 10 through 13 but the readme states 10 and 11. Thanks!

**Comment by stevetemple** [comment]
Yes it is 

You'll just need to change the Icon to "icon-microsoft-fill", i.e. "Icon": "icon-microsoft-fill", in v13 (it's in the readme)
